version: "3.3"
services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_database
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
volumes:
  db_data: